require: rubocop-rspec
inherit_from:
  - .rubocop-disabled.yml

AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - config/deploy/*
    - config/deploy.rb
    - sandbox/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'db/migrate/*.rb'
    - Guardfile
    - '**/*_spec.rb'
    - db/schema.rb
    - config/routes.rb
    - spec/rails_helper.rb
    - spec/spec_helper.rb

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*.rb'
    - Guardfile
    - '**/*_spec.rb'
    - config/routes.rb

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'
    - Guardfile
    - '**/*_spec.rb'
    - config/routes.rb

Naming/AccessorMethodName:
  Exclude:
    - 'app/datatables/*.rb'

RSpec/MultipleExpectations:
  Max: 10

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
