## This
version: '3'
services:
  db:
    image: postgres:9.6
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: dev.dockerfile
    command: rails s -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - POSKO_DATABASE_HOST=db
      - POSKO_DATABASE_USERNAME=postgres
      - POSKO_DATABASE_PASSWORD=''
    depends_on:
      - db
