default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSKO_DATABASE_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("POSKO_DATABASE_USERNAME") { 5 } %>
  password: <%= ENV['POSKO_DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: posko_development

test:
  <<: *default
  database: posko_test

staging:
  <<: *default
  database: <%= ENV.fetch('POSKO_DATABASE_NAME') { 'posko_staging' }

production:
  <<: *default
  database: <%= ENV.fetch('POSKO_DATABASE_NAME') { 'posko_production' }
